// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_StartSlideshow(lv_event_t * e)
{
	// Your code here
}

void ui_event_FolderSelector(lv_event_t * e)
{
	// Your code here
}

void ui_event_SlideshowDuration(lv_event_t * e)
{
	// Your code here
}

void ui_event_GrokImageGeneration(lv_event_t * e)
{
	// Your code here
}

void ui_event_GrokDuration(lv_event_t * e)
{
	// Your code here
}

void ui_event_setsettings(lv_event_t * e)
{
	// Your code here
}

void ui_event_autoplay(lv_event_t * e)
{
	// Your code here
}
