// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_StartSlideshow(lv_event_t * e);
void ui_event_FolderSelector(lv_event_t * e);
void ui_event_SlideshowDuration(lv_event_t * e);
void ui_event_GrokImageGeneration(lv_event_t * e);
void ui_event_GrokDuration(lv_event_t * e);
void ui_event_setsettings(lv_event_t * e);
void ui_event_autoplay(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
