// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_show_screen_init(void)
{
    ui_show = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_show, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_button_create(ui_show);
    lv_obj_set_width(ui_Button4, 140);
    lv_obj_set_height(ui_Button4, 70);
    lv_obj_set_x(ui_Button4, 640);
    lv_obj_set_y(ui_Button4, 390);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 127, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button4, lv_color_hex(0x1B31E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button4, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button4, lv_color_hex(0xADD8E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button4, 127, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Button4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button4, lv_color_hex(0x3B3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button4, &ui_font_Roboto_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Button4, 8, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button4, 50, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Button4, lv_color_hex(0x1B31E7), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Button4, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_Button4, lv_color_hex(0xADD8E6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_Button4, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(ui_Button4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Button4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_align(ui_Button4, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_font(ui_Button4, &ui_font_Roboto_Bold, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label6 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "to main...");

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_show, ui_event_show, LV_EVENT_ALL, NULL);

}
